version: '3.8'

services:
  api:
    image: satsuro/glossary-backend:latest
    container_name: glossary_backend
    platform: linux/amd64
    ports:
      - "8000:8000"
    volumes:
      - ./backend/glossary.json:/app/glossary.json
    restart: always

  web:
    image: satsuro/glossary-frontend:latest
    container_name: glossary_frontend
    platform: linux/amd64
    ports:
      - "3000:80"
    depends_on:
      - api
    restart: always
